name: Bixel St Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36265
title: Bixel St Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#20201e'
    - '#ff3f54'
    - '#8b755d'
    - '#e2d0bc'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
