name: Bixel St Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60736
title: Bixel St Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#333335'
    - '#f2f2f4'
    - '#f2bda2'
    - '#b03a25'
  brandStrength: 0.23691426194272935
  lightness: 0.7190239981282502
  saturation: 0.8046417746227235
  rhythmicContrast: 0.8880779736209661
purpose: []
